import { Facebook, Instagram, Twitter, ArrowUpRight } from 'lucide-react'
import { Link } from 'react-router-dom'
import logoImg from '../../Final_File_Omicron_Journeys_Logo/Final_File_Omicron_Journeys_Logo/Final_Omicron_Journeys_Logo-01.png'
import './Footer.css'
export default function Footer(){return <footer className="footer">
 <div className="container footer-main">
  <div className="footer-brand"><Link to="/" aria-label="Omicron Journeys home"><img src={logoImg} alt="Omicron Journeys" className="footer-logo-img"/></Link><h2>Go further.<br/>Travel thoughtfully.</h2><p>Vehicle rentals, personalized tours and shared adventures, planned with comfort and care.</p><div className="footer-social"><a href="https://www.facebook.com/share/XEUoQ1UA913WyJfz/" target="_blank" rel="noreferrer" aria-label="Facebook"><Facebook size={17}/></a><a href="https://www.instagram.com/omicronjourneys/" target="_blank" rel="noreferrer" aria-label="Instagram"><Instagram size={17}/></a><a href="https://x.com/Omicronjourneys" target="_blank" rel="noreferrer" aria-label="X"><Twitter size={17}/></a></div></div>
  <div><div className="footer-title">Explore</div><div className="footer-links"><Link to="/services">Services</Link><Link to="/#packages">Tour Packages</Link><Link to="/fleet">Our Fleet</Link><Link to="/blog">Travel Blog</Link><Link to="/about">About Us</Link><Link to="/contact">Contact</Link></div></div>
  <div><div className="footer-title">Your journey</div><div className="footer-links"><Link to="/fleet">Vehicle Rental</Link><Link to="/luxury">Luxury Vehicles</Link><Link to="/services">Customized Domestic Tours</Link><Link to="/#packages">Group Packages</Link></div></div>
  <div><div className="footer-title">Let’s talk travel</div><div className="contact-copy"><a href="tel:+919322115828">+91 93221 15828</a><a href="tel:+917620020040">+91 76200 20040</a><a href="mailto:info@omicronjourneys.com">info@omicronjourneys.com</a><div>Plot no. 202, Nagar Rd, CIDCO Waluj Mahanagar 2,<br/>Aurangabad, Maharashtra 431136</div><a href="https://www.google.com/maps/search/?api=1&query=Omicron%20Journeys%20CIDCO%20Waluj%20Mahanagar%202%20Aurangabad" target="_blank" rel="noreferrer">Find us on Maps <ArrowUpRight size={13}/></a></div></div>
 </div><div className="footer-bottom"><span>© {new Date().getFullYear()} Omicron Journeys Pvt. Ltd.</span><span>Thoughtful travel. Memorable journeys.</span></div>
 </footer>}
